// Code generated by Random TypeScript Code Generator. DO NOT EDIT.

interface SchoolProject {
    repoName: "SchoolProject";
    files: File[];
}

interface File {
    name: string;
    contents: string;
}

const schoolProject: SchoolProject = {
    repoName: "SchoolProject",
    files: [
        {
            name: "main.ts",
            contents: `import { Person } from "./person";

const person1: Person = {
    name: "John Doe",
    age: 30,
    job: "Software Engineer"
};

console.log(person1);
`,
        },
        {
            name: "person.ts",
            contents: `export interface Person {
    name: string;
    age: number;
    job: string;
}`,
        },
    ],
};

export default schoolProject;
